server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:schoolDigitalAgenda/SDAConfigRepo.git
          clone-on-start: true

  security:
    user:
      name: ${SECURITY_USER_NAME:root}
      password: ${SECURITY_USER_PASSWORD:s3cr3t}
