apiVersion: v1
kind: Service
metadata:
  name: sda-config-server
spec:
  type: NodePort
  selector:
    app: sda-config-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31231

